# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/awerkiler/progs/Mail/old1/AdvancedC ++/Project/7"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/awerkiler/progs/Mail/old1/AdvancedC ++/Project/7"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/awerkiler/progs/Mail/old1/AdvancedC ++/Project/7/CMakeFiles" "/home/awerkiler/progs/Mail/old1/AdvancedC ++/Project/7/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/awerkiler/progs/Mail/old1/AdvancedC ++/Project/7/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KDDB

# Build rule for target.
KDDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KDDB
.PHONY : KDDB

# fast build rule for target.
KDDB/fast:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/build
.PHONY : KDDB/fast

Base/BaseContainer.o: Base/BaseContainer.cpp.o

.PHONY : Base/BaseContainer.o

# target to build an object file
Base/BaseContainer.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseContainer.cpp.o
.PHONY : Base/BaseContainer.cpp.o

Base/BaseContainer.i: Base/BaseContainer.cpp.i

.PHONY : Base/BaseContainer.i

# target to preprocess a source file
Base/BaseContainer.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseContainer.cpp.i
.PHONY : Base/BaseContainer.cpp.i

Base/BaseContainer.s: Base/BaseContainer.cpp.s

.PHONY : Base/BaseContainer.s

# target to generate assembly for a file
Base/BaseContainer.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseContainer.cpp.s
.PHONY : Base/BaseContainer.cpp.s

Base/BaseDB.o: Base/BaseDB.cpp.o

.PHONY : Base/BaseDB.o

# target to build an object file
Base/BaseDB.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDB.cpp.o
.PHONY : Base/BaseDB.cpp.o

Base/BaseDB.i: Base/BaseDB.cpp.i

.PHONY : Base/BaseDB.i

# target to preprocess a source file
Base/BaseDB.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDB.cpp.i
.PHONY : Base/BaseDB.cpp.i

Base/BaseDB.s: Base/BaseDB.cpp.s

.PHONY : Base/BaseDB.s

# target to generate assembly for a file
Base/BaseDB.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDB.cpp.s
.PHONY : Base/BaseDB.cpp.s

Base/BaseDataStructure.o: Base/BaseDataStructure.cpp.o

.PHONY : Base/BaseDataStructure.o

# target to build an object file
Base/BaseDataStructure.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDataStructure.cpp.o
.PHONY : Base/BaseDataStructure.cpp.o

Base/BaseDataStructure.i: Base/BaseDataStructure.cpp.i

.PHONY : Base/BaseDataStructure.i

# target to preprocess a source file
Base/BaseDataStructure.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDataStructure.cpp.i
.PHONY : Base/BaseDataStructure.cpp.i

Base/BaseDataStructure.s: Base/BaseDataStructure.cpp.s

.PHONY : Base/BaseDataStructure.s

# target to generate assembly for a file
Base/BaseDataStructure.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseDataStructure.cpp.s
.PHONY : Base/BaseDataStructure.cpp.s

Base/BaseSearchEngine.o: Base/BaseSearchEngine.cpp.o

.PHONY : Base/BaseSearchEngine.o

# target to build an object file
Base/BaseSearchEngine.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseSearchEngine.cpp.o
.PHONY : Base/BaseSearchEngine.cpp.o

Base/BaseSearchEngine.i: Base/BaseSearchEngine.cpp.i

.PHONY : Base/BaseSearchEngine.i

# target to preprocess a source file
Base/BaseSearchEngine.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseSearchEngine.cpp.i
.PHONY : Base/BaseSearchEngine.cpp.i

Base/BaseSearchEngine.s: Base/BaseSearchEngine.cpp.s

.PHONY : Base/BaseSearchEngine.s

# target to generate assembly for a file
Base/BaseSearchEngine.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/Base/BaseSearchEngine.cpp.s
.PHONY : Base/BaseSearchEngine.cpp.s

KD/Container.o: KD/Container.cpp.o

.PHONY : KD/Container.o

# target to build an object file
KD/Container.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/Container.cpp.o
.PHONY : KD/Container.cpp.o

KD/Container.i: KD/Container.cpp.i

.PHONY : KD/Container.i

# target to preprocess a source file
KD/Container.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/Container.cpp.i
.PHONY : KD/Container.cpp.i

KD/Container.s: KD/Container.cpp.s

.PHONY : KD/Container.s

# target to generate assembly for a file
KD/Container.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/Container.cpp.s
.PHONY : KD/Container.cpp.s

KD/DB.o: KD/DB.cpp.o

.PHONY : KD/DB.o

# target to build an object file
KD/DB.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DB.cpp.o
.PHONY : KD/DB.cpp.o

KD/DB.i: KD/DB.cpp.i

.PHONY : KD/DB.i

# target to preprocess a source file
KD/DB.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DB.cpp.i
.PHONY : KD/DB.cpp.i

KD/DB.s: KD/DB.cpp.s

.PHONY : KD/DB.s

# target to generate assembly for a file
KD/DB.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DB.cpp.s
.PHONY : KD/DB.cpp.s

KD/DBManager.o: KD/DBManager.cpp.o

.PHONY : KD/DBManager.o

# target to build an object file
KD/DBManager.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DBManager.cpp.o
.PHONY : KD/DBManager.cpp.o

KD/DBManager.i: KD/DBManager.cpp.i

.PHONY : KD/DBManager.i

# target to preprocess a source file
KD/DBManager.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DBManager.cpp.i
.PHONY : KD/DBManager.cpp.i

KD/DBManager.s: KD/DBManager.cpp.s

.PHONY : KD/DBManager.s

# target to generate assembly for a file
KD/DBManager.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/DBManager.cpp.s
.PHONY : KD/DBManager.cpp.s

KD/KDTree.o: KD/KDTree.cpp.o

.PHONY : KD/KDTree.o

# target to build an object file
KD/KDTree.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/KDTree.cpp.o
.PHONY : KD/KDTree.cpp.o

KD/KDTree.i: KD/KDTree.cpp.i

.PHONY : KD/KDTree.i

# target to preprocess a source file
KD/KDTree.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/KDTree.cpp.i
.PHONY : KD/KDTree.cpp.i

KD/KDTree.s: KD/KDTree.cpp.s

.PHONY : KD/KDTree.s

# target to generate assembly for a file
KD/KDTree.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/KDTree.cpp.s
.PHONY : KD/KDTree.cpp.s

KD/SearchEngine.o: KD/SearchEngine.cpp.o

.PHONY : KD/SearchEngine.o

# target to build an object file
KD/SearchEngine.cpp.o:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/SearchEngine.cpp.o
.PHONY : KD/SearchEngine.cpp.o

KD/SearchEngine.i: KD/SearchEngine.cpp.i

.PHONY : KD/SearchEngine.i

# target to preprocess a source file
KD/SearchEngine.cpp.i:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/SearchEngine.cpp.i
.PHONY : KD/SearchEngine.cpp.i

KD/SearchEngine.s: KD/SearchEngine.cpp.s

.PHONY : KD/SearchEngine.s

# target to generate assembly for a file
KD/SearchEngine.cpp.s:
	$(MAKE) -f CMakeFiles/KDDB.dir/build.make CMakeFiles/KDDB.dir/KD/SearchEngine.cpp.s
.PHONY : KD/SearchEngine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... KDDB"
	@echo "... edit_cache"
	@echo "... Base/BaseContainer.o"
	@echo "... Base/BaseContainer.i"
	@echo "... Base/BaseContainer.s"
	@echo "... Base/BaseDB.o"
	@echo "... Base/BaseDB.i"
	@echo "... Base/BaseDB.s"
	@echo "... Base/BaseDataStructure.o"
	@echo "... Base/BaseDataStructure.i"
	@echo "... Base/BaseDataStructure.s"
	@echo "... Base/BaseSearchEngine.o"
	@echo "... Base/BaseSearchEngine.i"
	@echo "... Base/BaseSearchEngine.s"
	@echo "... KD/Container.o"
	@echo "... KD/Container.i"
	@echo "... KD/Container.s"
	@echo "... KD/DB.o"
	@echo "... KD/DB.i"
	@echo "... KD/DB.s"
	@echo "... KD/DBManager.o"
	@echo "... KD/DBManager.i"
	@echo "... KD/DBManager.s"
	@echo "... KD/KDTree.o"
	@echo "... KD/KDTree.i"
	@echo "... KD/KDTree.s"
	@echo "... KD/SearchEngine.o"
	@echo "... KD/SearchEngine.i"
	@echo "... KD/SearchEngine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

